icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome4"
#[icons.overrides]
#bat = ["|E|", "|_|", "|-|", "|F|"]
#bat_charging = "|^| "

[[block]]
block = "battery"
interval = 60
full_format = " $icon $percentage "
empty_format = " $icon $time_remaining "
charging_format = " $icon $time_remaining "
info = 81
good = 51
warning = 21
critical = 11

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %Y-%m-%d %R') " 
